### ISSUE TITLE
[Question] Does upsert update ID values

### ISSUE THREAD

**Issue by kzeitz** [streamx-co/try.elinq#11]
All I would like to do is this...
Create say 3 'tag' entities.  'Upsert' those entities so the entities have the correct ID from the backing tags table (whether the tag already existed or not) and have the 'tag' entity state update in the ef changeTracker correctly.  So when I later call SaveChanges() I don't generate key violations.

Can I accomplish this try.elinq?

**Comment by kostat** [comment]
Basically this is a question about EF change tracking, unrelated to EntityLinq. If I understand you correctly you want to mark 'tag' entities unchanged after `Upsert`. I think [this is the answer](https://docs.microsoft.com/en-us/ef/ef6/saving/change-tracking/entity-state#changing-the-state-of-a-tracked-entity).
Generally better to ask such questions in StackOverflow, you will get a much faster response.
