### ISSUE TITLE
[Question] How does elinq use specific alias?

### ISSUE THREAD

**Issue by shcant** [streamx-co/try.elinq#12]
In was using this awesome library and i noticed i needed to set an alias, but there was no option to do so. For example:

```C#
SELECT<T>( t.Operation.@as("__$operation"), t.StartLsn.@as("__$start_lsn"),  t.EndLsn.@as("__$end_lsn"));
```

It would be helpful to allow for setting this.

**Comment by kostat** [comment]
@shcant : can you please please tell the reason you need to set an alias and provide a full use case?

**Comment by shcant** [comment]
> @shcant : can you please please tell the reason you need to set an alias and provide a full use case?

Sorry for the late reply. Seems like i can set alias using ef core. Thanks for your help.
