### ISSUE TITLE
Bug about literal

### ISSUE THREAD

**Issue by shcant** [streamx-co/try.elinq#16]
I want to use one literal as two different columns, but elinq generated SQL has same column name. How can I do it ?

![image](https://user-images.githubusercontent.com/16911353/208398492-07e0837a-a570-4acb-a7b1-a74b07d3a76d.png)

any help will be appreciated.

**Comment by kostat** [comment]
@shcant , unfortunately I don't understand the problem you experience. Can you please provide the C# code in textual form (not picture) + expected SQL + actual SQL?

**Comment by kostat** [comment]
@shcant , I'm hence closing the issue as not reproduced. Please feel free to add more details and reopen.
