### ISSUE TITLE
Cannot build a DELETE with RETURNING clause with Postgres Vendor

### ISSUE THREAD

**Issue by vaibhavpingle** [streamx-co/try.elinq#2]
I have been using this awesome library with Npgsql.EntityFramework.Core package. I am trying to write a DELETE RETURNING and struggling with the same. Can you please help me with the same?

**Comment by kostat** [comment]
Please provide entity definitions, Entity LINQ statement and the exception thrown.
In case you have an SQL statement, but can't express it in Entity LINQ, please provide the statement as well

**Comment by vaibhavpingle** [comment]
@kostat Thanks for looking into this. Here is what I am trying to write using ELinq:

`with to_delete as (
    select *
    from some_table
    limit 10
)
delete from some_table as md
using to_delete as td
where md.Id = td.Id
returning *;`

The table 'some_table' has an Id column and other columns which are not relevant to what I am trying to solve. I am deleting records and then processing them on the application side.

**Comment by kostat** [comment]
@vaibhavpingle: I assume you are looking for something like this:

```cs
db.Links.Query((LinkTmp linkTmp) => {

    var toDelete = SubQuery((Link link) => {
        var r = SELECT(link);
        FROM(link);
        LIMIT(10);
        return r;
    });

    WITH(toDelete);

    DELETE().FROM(linkTmp).USING(toDelete);
    WHERE(toDelete.Id == linkTmp.Id);

    return RETURNING(linkTmp);

});
```

which produces the following SQL:

```SQL
WITH q0 AS 
(SELECT t1.*
FROM link AS t1
LIMIT 10)
DELETE   FROM link AS t0  USING q0
WHERE (q0.Id = t0.Id)
RETURNING t0.*
```

**Comment by vaibhavpingle** [comment]
@kostat the query generated does not have the alias for link As t0. Hence the Id in the where clause becomes ambiguous. Now I see that you have linkTmp object for the outer main query. Why is that and where do I define that if I want to do something similar.

**Comment by kostat** [comment]
I suspect that you forgot to `RegisterVendorCapabilities()` for Postgres. (Each vendor has slightly different aliasing rules).

Please see https://github.com/streamx-co/try.elinq/blob/master/Setup.md. Eventually you need to call `Streamx.Linq.SQL.PostgreSQL.SQL.RegisterVendorCapabilities()` extension method.

BTW, there is nothing special in my entities:

```cs
[Table("link")]
public class Link {
    public int Id { get; set; }
}

public class LinkTmp : Link { }
...
modelBuilder.Entity<Link>(b => { });
modelBuilder.Entity<LinkTmp>(b => { });
```

So if my assumption is wrong, please provide your ELINQ method, entity definitions and produced SQL.

**Comment by vaibhavpingle** [comment]
@kostat - Thank you. That fixed my issue. I think reruning the scaffolding i lost that particular registration in the Context as it overwrites any modifications to it. I now have it called in a separate place where I call it as a part of the DI in startup.cs so that i dont lose that call going forward when i run the scaffolding again.

Thank you also for the clarification of the LinkTmp. I did not have them as that so i could just work with a single table.

There was however another issue that i wanted to bring up about models generated for PostGIS datatypes. I got some error when one of my column data types were of type geometry/geography, and it was unable to generate the query for me. could it also be possible due to me missing that VendorRegistration call? or is it a functionality that is yet to be supported by ELinq? Below was my code that i was using to generate my query and the Deadhead entity.
```C#
 [Table("deadhead")]
    public partial class Deadhead
    {
        [Column("origin_lon", TypeName = "numeric")]
        public decimal OriginLon { get; set; }
        [Column("origin_lat", TypeName = "numeric")]
        public decimal OriginLat { get; set; }
        [Column("destination_lon", TypeName = "numeric")]
        public decimal DestinationLon { get; set; }
        [Column("destination_lat", TypeName = "numeric")]
        public decimal DestinationLat { get; set; }
        [Column("distance", TypeName = "numeric")]
        public decimal Distance { get; set; }
        [Key]
        [Column("key", TypeName = "character varying")]
        public string Key { get; set; }
        [Column("origin_point")]
        public NpgsqlPoint? OriginPoint { get; set; }
        [Column("destination_point")]
        public NpgsqlPoint? DestinationPoint { get; set; }
        [Column("origin_geog", TypeName = "geography")]
        public Geometry OriginGeog { get; set; }
        [Column("destination_geog", TypeName = "geography")]
        public Geometry DestinationGeog { get; set; }
    }

db.Deadhead.Query((Deadhead deadhead) =>
{
var view = deadhead.@using((deadhead.Key, deadhead.OriginLon, deadhead.OriginLat, deadhead.DestinationLon, deadhead.DestinationLat, deadhead.Distance, deadhead.OriginPoint, deadhead.DestinationPoint, deadhead.OriginGeog, deadhead.DestinationGeog));
INSERT().INTO(view);
VALUES(view.RowsFrom(upsertData));
ON_CONFLICT((deadhead.OriginLon, deadhead.OriginLat, deadhead.DestinationLon, deadhead.DestinationLat)).DO_NOTHING();
return RETURNING(deadhead);
});
```

**Comment by kostat** [comment]
@vaibhavpingle: I'm closing this issue since it's resolved. I created a new one - #3 for tracking the last problem. From your description I think that I figured the problem, but if you could add the exception stack trace, I will be confident that I'm working on the right thing. Please add it to the linked issue.
