### ISSUE TITLE
Jsonb columns not working

### ISSUE THREAD

**Issue by vaibhavpingle** [streamx-co/try.elinq#4]
I have some jsonb columns in my table with postgres.Th error looks like No RelationalType for the CLR type SomeJsonbClass.

Is there no jsonb support?
`
System.InvalidOperationException: No mapping to a relational type can be found for the CLR type 'LoadStopDocument'. at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSourceExtensions.GetMapping(IRelationalTypeMappingSource typeMappingSource, Type clrType) at Microsoft.EntityFrameworkCore.Storage.Internal.DynamicRelationalParameter.AddDbParameter(DbCommand command, Object value) at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary2 parameterValues) at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod) at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject) at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable1 parameters) at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, Object[] parameters) at Streamx.Linq.SQL.EFCore.EFCoreExtensions.A[A](DatabaseFacade , A ) at Streamx.Linq.SQL.EFCore.EFCoreExtensions.Execute[TEntity](DatabaseFacade source, Action1 query) at 
`

**Comment by kostat** [comment]
There is no "special" jsonb support. Yet, what is the use case and how EF
core behaves there?

Kosta

**Comment by vaibhavpingle** [comment]
We are using elinq on top of npgsql on top of efcore. Without elinq, npgsql is able to easily handle the jsonb as documented on https://www.npgsql.org/efcore/mapping/json.html?tabs=data-annotations%2Cpoco. We were already using it, but the need came to change this application to perform bulk 'insert if not exist' logic, that is where we wanted to leverage elinq.
We did find a work around while still using elinq, by updating the generated model class to have a property of type `System.Text.Json.JsonDocument` and because for this particular application, we are mainly only writing data and not reading, we were able to convert our object to JsonDocument right before we inserted by running the following snippet: `System.Text.Json.JsonDocument.Parse(System.Text.Json.JsonSerializer.Serialize(someJsonObject))`.
But as you can see storing this as JsonDocument isn't the most beautiful code or as efficient.
I am pretty sure you could using some Npgsql magic that can will allow us to not define the property type to be any Class type that we define.

**Comment by kostat** [comment]
ELinq does not work directly with drivers/providers. It interfaces only
with EF Core.

So the question is if you are able to map your jsonb columns and then
save/retrieve data using DbContext? This is crucial because of the above.

It would be also helpful to see the actual code you are trying to run and
the exception you get

**Comment by kostat** [comment]
Unfortunately I need to correct you: ... elinq on top of efcore on top of npgsql.
ELinq does not work directly with drivers/providers. It's an extension to EF core and it interfaces with it only. So if 
RelationalDatabaseFacadeExtensions.ExecuteSqlRaw is unable to map parameters/results, there is no workaround.
