### ISSUE TITLE
[Question] Is it possible to have an example of selecting all fields of a entity (e.g. SELECT * FROM TABLE in Sql) ?

### ISSUE THREAD

**Issue by fededim** [streamx-co/try.elinq#6]
Unluckily most of the [documentation](https://github.com/streamx-co/try.elinq/blob/d10590c5fc9e73690ab97ff2c720050e3ce94f45/docs/SqlServerTutorial/Select.md) is empty!

p.s. obviously I do not want to explicit all columns!

**Comment by kostat** [comment]
The documentation is designed to work using [try .net tool](https://dotnet.microsoft.com/platform/try-dotnet)

To access it, you may either browse the [live documentation site](https://try.entitylinq.com/) or [run the site locally](https://github.com/streamx-co/try.elinq/blob/master/RunLocally.md)

**Comment by fededim** [comment]
Ok thanks I found the documentation [here](https://try.entitylinq.com/docs/SqlServerTutorial/Select.md)
